### ISSUE TITLE
Install Kali on WSL (30)

### ISSUE THREAD

**Issue by dogwynn** [lowlandresearch/cate-lukner-internship#1]
Bounty: $30

https://www.kali.org/news/kali-linux-in-the-windows-app-store/

Please keep detailed notes on your experience. That is part of the bounty. Put documentation in a directory (`kali-wsl`) in this repo. 

- Certainly a `README.md` file, but there might be other scripts, etc. that you might include.
- Any problems encountered, please document what they are and how you overcome them.

**Comment by Cate-Michalska** [comment]
Completed. I will commit once we have forking figured out.
